repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ["--manifest-path", "./backend/Cargo.toml"]
  - repo: local
    hooks:
      - id: auto-changelog
        name: auto-changelog
        description: Generate a changelog from git metadata
        language: system
        files: CHANGELOG.md
        entry: auto-changelog
        args:
          - --hide-credit
          - --template
          - keepachangelog
          - --output
          - CHANGELOG.md
