"$schema" = "./schemas/desktop-schema.toml"
identifier = "main-capability"
description = "Capability for the main window"
windows = ["main", "walletConnect"]
permissions = [
  "path:default",
  "event:default",
  "event:allow-listen",
  "window:default",
  "window:allow-create",
  "window:allow-close",
  "window:allow-set-title",
  "webview:allow-create-webview-window",
  "webview:default",
  "app:default",
  "resources:default",
  "menu:default",
  "tray:default",
]
