"$schema" = "./schemas/desktop-schema.toml"
identifier = "main-capability"
description = "Capability for the main window"
windows = ["main", "wallet-connect"]
permissions = [
    "path:default",
    "event:default",
    "event:allow-listen",
    "window:default",
    "window:allow-create",
    "window:allow-close",
    "updater:allow-check",
    "updater:default",
    "process:allow-restart",
    "window:allow-set-title",
    "window:allow-destroy",
    "webview:allow-create-webview-window",
    "webview:allow-create-webview",
    "webview:allow-webview-close",
    "webview:default",
    "app:default",
    "resources:default",
    "menu:default",
    "tray:default",
]
