name: "Build Tauri Android App"

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 19.8.1

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup android NDK
        run: |
          sdkmanager "ndk;25.2.9519653" "platform-tools" "platforms;android-30"
          echo 'NDK_HOME='$ANDROID_HOME'/ndk/25.2.9519653/' >> $GITHUB_ENV

      - name: Install Tauri dependencies
        run: >-
          sudo apt-get update &&
          sudo apt install -yqq
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          webkit2gtk-driver
          xvfb
          curl
          wget
          sdkmanager
          build-essential
          libssl-dev
          librsvg2-dev

      - name: Install Tauri
        run: |
          cargo install create-tauri-app
          rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
          cargo install tauri-cli --version "^2.0.0-alpha.10"

      - name: Install NPM dependencies
        run: |
          cd ./tauri_app/frontend
          npm install

      - run: cargo tauri info

      - name: Build Android App
        env:
          NDK_HOME: ${{ env.NDK_HOME }}
          RANLIB: ${{ env.NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
         
        run: |
          ./tauri_app/scripts/gen-config.sh
           cargo tauri android init
           cargo tauri android build

      # - name: Release APK
      #   uses: docker://antonyurchenko/git-release:v5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITHUB_REF: ${{ github.ref }}
      #     PRE_RELEASE: "true"
      #     RELEASE_NAME_SUFFIX: " (dev build)"
      #     CHANGELOG_FILE: "CHANGELOG.md"
      #   with:
      #     args: /home/runner/work/avail_mobile/avail_mobile/backend/gen/android/app/build/outputs/apk/universal/release/*.apk
