name: Tauri Build

on:
  pull_request:
    branches: [ develop, staging, release ]

# This workflow will build your tauri app without uploading it anywhere.

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
  build:
    needs: pre-commit
    environment: ${{ github.ref_name }}
    permissions:
        contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Initialize Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsoup-3.0-dev libwebkit2gtk-4.1-dev patchelf javascriptcoregtk-4.1 build-essential curl wget file libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install Tauri CLI using Cargo
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tauri-cli
          version: "2.0.0-beta.1"

      - uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY}}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD}}
          API: ${{ secrets.AVAIL_API_URL}}
          DEV_NODE_IP: ${{ secrets.DEV_NODE_IP}}
          TESTNET_API_OBSCURA: ${{ secrets.TESTNET_API_OBSCURA}}
          MAINNET_API_OBSCURA: ""
          DEVNET_API_OBSCURA: ""
        with:
            distPath: dist
